DROP TABLE credits;

CREATE TABLE `credits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=471 DEFAULT CHARSET=utf8;

INSERT INTO credits VALUES("269","Abdelbasset Amara");
INSERT INTO credits VALUES("408","Adam Ujvari");
INSERT INTO credits VALUES("17","Adrian Schnedlitz");
INSERT INTO credits VALUES("87","Aiman Awwad");
INSERT INTO credits VALUES("56","Ainul Husna Abdul Muin");
INSERT INTO credits VALUES("16","Ajdin Vihric");
INSERT INTO credits VALUES("59","Alex Nicoara");
INSERT INTO credits VALUES("41","Alexander Gütler");
INSERT INTO credits VALUES("103","Alexander Kalchauer");
INSERT INTO credits VALUES("438","Alexander Kargl");
INSERT INTO credits VALUES("254","Alexander Oberbucher");
INSERT INTO credits VALUES("244","Alexander Oberegger");
INSERT INTO credits VALUES("348","Alexander Wieland");
INSERT INTO credits VALUES("93","Alexei Nicoara");
INSERT INTO credits VALUES("407","Amel Hamidovic");
INSERT INTO credits VALUES("9","Amra Dzombic");
INSERT INTO credits VALUES("385","André Tropper");
INSERT INTO credits VALUES("167","Andrea Höfler");
INSERT INTO credits VALUES("230","Andreas Abraham");
INSERT INTO credits VALUES("188","Andreas Frühwirt");
INSERT INTO credits VALUES("322","Andreas Gladik");
INSERT INTO credits VALUES("291","Andreas Hofbauer");
INSERT INTO credits VALUES("163","Andreas Maureder");
INSERT INTO credits VALUES("286","Andreas Müller");
INSERT INTO credits VALUES("243","Andreas Voraberger");
INSERT INTO credits VALUES("419","Andrej Knaus");
INSERT INTO credits VALUES("84","Andrej Müller");
INSERT INTO credits VALUES("362","Andrew Deutschmann");
INSERT INTO credits VALUES("225","Angelika Droisner");
INSERT INTO credits VALUES("155","Angelika More");
INSERT INTO credits VALUES("1","Anja Petri");
INSERT INTO credits VALUES("468","Anja Reibenbacher");
INSERT INTO credits VALUES("378","Anna Lickl");
INSERT INTO credits VALUES("102","Annemarie Harzl");
INSERT INTO credits VALUES("42","Anton Rieder");
INSERT INTO credits VALUES("92","Anton Stjernst");
INSERT INTO credits VALUES("288","Armend Zeqiraj");
INSERT INTO credits VALUES("239","Armin Hutzler");
INSERT INTO credits VALUES("302","Armin Wieser");
INSERT INTO credits VALUES("96","Arnan Roger Sipitakiat");
INSERT INTO credits VALUES("217","Arno Stauder");
INSERT INTO credits VALUES("299","Artur Knaus");
INSERT INTO credits VALUES("196","Artur Termenji");
INSERT INTO credits VALUES("80","B Maciek");
INSERT INTO credits VALUES("386","Benjamin Bristow");
INSERT INTO credits VALUES("69","Benjamin Grant");
INSERT INTO credits VALUES("460","Benjamin Wullschleger");
INSERT INTO credits VALUES("383","Bernadette Spieler");
INSERT INTO credits VALUES("339","Bernd Baumann");
INSERT INTO credits VALUES("204","Bernhard Ruttinger");
INSERT INTO credits VALUES("38","Bernhard Spitzer");
INSERT INTO credits VALUES("146","Bernhard Trapp");
INSERT INTO credits VALUES("326","Bernhard Winter");
INSERT INTO credits VALUES("389","Bianca Jakobitsch");
INSERT INTO credits VALUES("232","Bianca Teufl");
INSERT INTO credits VALUES("142","Boris Kanjer");
INSERT INTO credits VALUES("347","Christian Benkovic");
INSERT INTO credits VALUES("310","Christian Burghard");
INSERT INTO credits VALUES("23","Christian Hartinger");
INSERT INTO credits VALUES("32","Christian Hofer");
INSERT INTO credits VALUES("465","Christian Huber");
INSERT INTO credits VALUES("393","Christian Jung");
INSERT INTO credits VALUES("457","Christian Leopold");
INSERT INTO credits VALUES("131","Christian Lesjak");
INSERT INTO credits VALUES("307","Christian M. Hofer");
INSERT INTO credits VALUES("357","Christian Reisinger");
INSERT INTO credits VALUES("387","Christian Schindler");
INSERT INTO credits VALUES("282","Christine Pichler");
INSERT INTO credits VALUES("382","Christof Rabensteiner");
INSERT INTO credits VALUES("189","Christof Stromberger");
INSERT INTO credits VALUES("363","Christoph Heidenreich");
INSERT INTO credits VALUES("137","Christoph Kahr");
INSERT INTO credits VALUES("255","Christoph Pilz");
INSERT INTO credits VALUES("444","Christoph Pozvek");
INSERT INTO credits VALUES("132","Christoph Woergoetter");
INSERT INTO credits VALUES("306","Christopher Immervoll");
INSERT INTO credits VALUES("268","Christopher Jelinek");
INSERT INTO credits VALUES("351","Claudio Kirchmair");
INSERT INTO credits VALUES("461","Clemens Stary");
INSERT INTO credits VALUES("31","Daniel Burtscher");
INSERT INTO credits VALUES("343","Daniel Ellmeier");
INSERT INTO credits VALUES("233","Daniel Franz Neuhold");
INSERT INTO credits VALUES("177","Daniel Fritzsch");
INSERT INTO credits VALUES("327","Daniel Ladenhauf");
INSERT INTO credits VALUES("435","Daniel Lintschinger");
INSERT INTO credits VALUES("29","Daniel Markart");
INSERT INTO credits VALUES("296","Daniel Neuhold");
INSERT INTO credits VALUES("281","Daniel Pail");
INSERT INTO credits VALUES("401","Daniel Rossmann");
INSERT INTO credits VALUES("208","Daniela Zierler");
INSERT INTO credits VALUES("8","Darjan Salaj");
INSERT INTO credits VALUES("443","David Kienreich");
INSERT INTO credits VALUES("138","David Kikelj");
INSERT INTO credits VALUES("249","David Kolb");
INSERT INTO credits VALUES("380","David Marogy");
INSERT INTO credits VALUES("436","David Niederkofler");
INSERT INTO credits VALUES("345","David Prott");
INSERT INTO credits VALUES("43","David Reisenberger");
INSERT INTO credits VALUES("256","David Strohmaier");
INSERT INTO credits VALUES("409","David Wittenbrink");
INSERT INTO credits VALUES("7","Davor Kirbis");
INSERT INTO credits VALUES("61","Deena Mugien");
INSERT INTO credits VALUES("427","Denis Munter");
INSERT INTO credits VALUES("58","Denise Hoo");
INSERT INTO credits VALUES("130","Dietmar Maurer");
INSERT INTO credits VALUES("462","Dino Keskic");
INSERT INTO credits VALUES("234","Domenik Melcher");
INSERT INTO credits VALUES("440","Dominik Lindenbauer");
INSERT INTO credits VALUES("251","Dominik Mößlang");
INSERT INTO credits VALUES("178","Dominik Schleicher");
INSERT INTO credits VALUES("253","Dominik Widnig");
INSERT INTO credits VALUES("280","Dominik Ziegler");
INSERT INTO credits VALUES("210","Eberhard Ferner");
INSERT INTO credits VALUES("308","Elena Mashkina");
INSERT INTO credits VALUES("235","Elisabeth Heschl");
INSERT INTO credits VALUES("439","Eric Gergely");
INSERT INTO credits VALUES("265","Eva-Maria Trummer");
INSERT INTO credits VALUES("257","Ewald Moitzi");
INSERT INTO credits VALUES("349","Fabian Hartl");
INSERT INTO credits VALUES("428","Fabian Kofler");
INSERT INTO credits VALUES("228","Fabian Tschiatschek");
INSERT INTO credits VALUES("66","Farhan Obisat");
INSERT INTO credits VALUES("60","Fatin Ghazi");
INSERT INTO credits VALUES("28","Ferdinand Knapitsch");
INSERT INTO credits VALUES("136","Florian Hubner");
INSERT INTO credits VALUES("198","Florian Schitter");
INSERT INTO credits VALUES("463","Florian Schneider");
INSERT INTO credits VALUES("162","Florian Sumann");
INSERT INTO credits VALUES("414","Florian Weißensteiner");
INSERT INTO credits VALUES("15","Florian Winkelbauer");
INSERT INTO credits VALUES("54","Franz Schreiner");
INSERT INTO credits VALUES("68","Gary Green");
INSERT INTO credits VALUES("402","Georg Schober");
INSERT INTO credits VALUES("221","Gerald Gsellmann");
INSERT INTO credits VALUES("340","Gerald Lohnauer");
INSERT INTO credits VALUES("157","Gerald Musser");
INSERT INTO credits VALUES("45","Gerald Wagner");
INSERT INTO credits VALUES("211","Gerhard Neuhold");
INSERT INTO credits VALUES("187","Gerhild Grinschgl");
INSERT INTO credits VALUES("369","Gerulf Binder");
INSERT INTO credits VALUES("97","Geuk Joong Bang");
INSERT INTO credits VALUES("258","Gottfried Selenko");
INSERT INTO credits VALUES("442","Gregor Liebisch");
INSERT INTO credits VALUES("21","Gregor Sitter");
INSERT INTO credits VALUES("86","Hajnalka Torma");
INSERT INTO credits VALUES("227","Hakan Özkan");
INSERT INTO credits VALUES("186","Hannes Hasenauer");
INSERT INTO credits VALUES("274","Hans Dieter Knaus");
INSERT INTO credits VALUES("135","Hans Peter Gugl");
INSERT INTO credits VALUES("147","Hans-Jürgen Schröttner");
INSERT INTO credits VALUES("433","Harald Schaffernak");
INSERT INTO credits VALUES("264","Hedwig Höller");
INSERT INTO credits VALUES("219","Heimo Ernst Bischofter");
INSERT INTO credits VALUES("169","Herbert Christian Lierzer");
INSERT INTO credits VALUES("453","Herbert Mikl");
INSERT INTO credits VALUES("70","Hulya Kara");
INSERT INTO credits VALUES("179","Ilija Simic");
INSERT INTO credits VALUES("375","Illya Boyko");
INSERT INTO credits VALUES("452","Ines Vorraber");
INSERT INTO credits VALUES("201","Ingrid Reip");
INSERT INTO credits VALUES("67","Ivan Venuti");
INSERT INTO credits VALUES("139","Jakob Strauss");
INSERT INTO credits VALUES("277","Jakob Unterkofler");
INSERT INTO credits VALUES("464","Jakov Matic");
INSERT INTO credits VALUES("470","Jamil Khan");
INSERT INTO credits VALUES("95","Jasmin Salihovic");
INSERT INTO credits VALUES("71","Jean Charpentier");
INSERT INTO credits VALUES("48","Jeton Arifi");
INSERT INTO credits VALUES("57","Jia Lin Chong");
INSERT INTO credits VALUES("467","Jiaqi Ning");
INSERT INTO credits VALUES("64","Jintae Lee");
INSERT INTO credits VALUES("434","Joachim Lesser");
INSERT INTO credits VALUES("83","João Filipe Matos");
INSERT INTO credits VALUES("432","Jochen Flachhuber");
INSERT INTO credits VALUES("134","Johannes Iber");
INSERT INTO credits VALUES("338","Johannes Kühnel");
INSERT INTO credits VALUES("321","Johannes Lüftenegger");
INSERT INTO credits VALUES("241","Johannes Singer");
INSERT INTO credits VALUES("394","Johannes Zenz");
INSERT INTO credits VALUES("98","Jordi LLi-Beltrán");
INSERT INTO credits VALUES("121","Jörg Hofer");
INSERT INTO credits VALUES("391","Josef Filzmaier");
INSERT INTO credits VALUES("205","Julia Schönhart");
INSERT INTO credits VALUES("450","Julia Viehberger");
INSERT INTO credits VALUES("353","Jürgen Wurzinger");
INSERT INTO credits VALUES("81","K Lalinea");
INSERT INTO credits VALUES("90","Kalpesh Surati");
INSERT INTO credits VALUES("246","Karl Koch");
INSERT INTO credits VALUES("10","Katharina Stadlmayr");
INSERT INTO credits VALUES("404","Kirshan Kumar Luhana");
INSERT INTO credits VALUES("99","Kuang Hui Tseng");
INSERT INTO credits VALUES("63","Kyoko Slany");
INSERT INTO credits VALUES("374","Laura Bebek");
INSERT INTO credits VALUES("459","Lea Novak");
INSERT INTO credits VALUES("6","Lisa Kehrer");
INSERT INTO credits VALUES("324","Luca Franceschini");
INSERT INTO credits VALUES("411","Lukas Fritz");
INSERT INTO credits VALUES("209","Lukas Krisper");
INSERT INTO credits VALUES("415","Lukas Loibnegger");
INSERT INTO credits VALUES("354","Lukas Mayr");
INSERT INTO credits VALUES("458","Lukas Pichler");
INSERT INTO credits VALUES("247","Lukas Prokop");
INSERT INTO credits VALUES("344","Lukas Radacher");
INSERT INTO credits VALUES("229","Lukas Resch");
INSERT INTO credits VALUES("180","Majda Osmic");
INSERT INTO credits VALUES("164","Manfred Knapp");
INSERT INTO credits VALUES("381","Manuel Haid");
INSERT INTO credits VALUES("300","Manuel Jelinek");
INSERT INTO credits VALUES("332","Manuel Polzhofer");
INSERT INTO credits VALUES("446","Manuel Schweiger");
INSERT INTO credits VALUES("51","Manuel Wallner");
INSERT INTO credits VALUES("128","Manuel Zoderer");
INSERT INTO credits VALUES("371","Marc Schober");
INSERT INTO credits VALUES("18","Marc Slavec");
INSERT INTO credits VALUES("285","Marco Meiser");
INSERT INTO credits VALUES("181","Marco Steger");
INSERT INTO credits VALUES("413","Marco Wallner");
INSERT INTO credits VALUES("101","Mardiyanto Saahi");
INSERT INTO credits VALUES("272","Maria Aumann");
INSERT INTO credits VALUES("4","Maria Schrack");
INSERT INTO credits VALUES("2","Mario Kolli");
INSERT INTO credits VALUES("379","Mario Lins");
INSERT INTO credits VALUES("422","Mario Pagger");
INSERT INTO credits VALUES("22","Marko Burazer");
INSERT INTO credits VALUES("305","Markus Hartmair");
INSERT INTO credits VALUES("14","Markus Hobisch");
INSERT INTO credits VALUES("46","Markus Hobl");
INSERT INTO credits VALUES("199","Markus Höfer");
INSERT INTO credits VALUES("360","Markus Nager");
INSERT INTO credits VALUES("423","Markus Reiter-Haas");
INSERT INTO credits VALUES("190","Markus Schmid");
INSERT INTO credits VALUES("78","Márta Turcsányi-Szabó");
INSERT INTO credits VALUES("250","Martin Burtscher");
INSERT INTO credits VALUES("301","Martin Erb");
INSERT INTO credits VALUES("437","Martin Kerschbaumer");
INSERT INTO credits VALUES("451","Martin Kurz");
INSERT INTO credits VALUES("129","Martin Oswald");
INSERT INTO credits VALUES("370","Martin Prinz");
INSERT INTO credits VALUES("449","Martin Zöhrer");
INSERT INTO credits VALUES("3","Martina Edelhofer");
INSERT INTO credits VALUES("412","Marvin Zechner");
INSERT INTO credits VALUES("260","Matthias Eichhaber");
INSERT INTO credits VALUES("26","Matthias Müller");
INSERT INTO credits VALUES("304","Matthias Schlesinger");
INSERT INTO credits VALUES("236","Matthias Sebastian Schlesinger");
INSERT INTO credits VALUES("174","Matthias Traub");
INSERT INTO credits VALUES("191","Mattias Rauter");
INSERT INTO credits VALUES("161","Max Löffler");
INSERT INTO credits VALUES("294","Max Reinthaler");
INSERT INTO credits VALUES("295","Max Schafzahl");
INSERT INTO credits VALUES("37","Maximilian Fellner");
INSERT INTO credits VALUES("182","Maximilian Sachs");
INSERT INTO credits VALUES("5","Melanie Kleindienst");
INSERT INTO credits VALUES("377","Michael Grebien");
INSERT INTO credits VALUES("352","Michael Herold");
INSERT INTO credits VALUES("261","Michael Koweindl");
INSERT INTO credits VALUES("420","Michael Lang");
INSERT INTO credits VALUES("396","Michael Maresch");
INSERT INTO credits VALUES("183","Michael Münzer");
INSERT INTO credits VALUES("231","Michael Peitler");
INSERT INTO credits VALUES("395","Michael Pittner");
INSERT INTO credits VALUES("172","Michael Pletz");
INSERT INTO credits VALUES("207","Michael Rabko");
INSERT INTO credits VALUES("184","Michael Rieder");
INSERT INTO credits VALUES("405","Michael Stessl");
INSERT INTO credits VALUES("298","Michael Stradner");
INSERT INTO credits VALUES("94","Mirhet Saracevic");
INSERT INTO credits VALUES("312","Namik Delilovic");
INSERT INTO credits VALUES("100","Nguyen Phuong Thao");
INSERT INTO credits VALUES("109","Nikolaus Koller");
INSERT INTO credits VALUES("11","Nikolaus Steininger");
INSERT INTO credits VALUES("355","Nikolaus Tiesenhausen");
INSERT INTO credits VALUES("222","Norbert Spot");
INSERT INTO credits VALUES("455","Oliver Papst");
INSERT INTO credits VALUES("111","Oliver Prentner");
INSERT INTO credits VALUES("421","Oliver Zott");
INSERT INTO credits VALUES("36","Othmar Ruprecht");
INSERT INTO credits VALUES("160","Otto Touzil");
INSERT INTO credits VALUES("89","Pabhasiri Mahatharadol");
INSERT INTO credits VALUES("85","Pascal Sengler");
INSERT INTO credits VALUES("388","Pascal Steiner");
INSERT INTO credits VALUES("202","Patman Ghazi");
INSERT INTO credits VALUES("425","Patrick Klampfl");
INSERT INTO credits VALUES("52","Patrick Koch");
INSERT INTO credits VALUES("426","Patrick Pongratz");
INSERT INTO credits VALUES("367","Patrick Radkohl");
INSERT INTO credits VALUES("384","Patrick Radl");
INSERT INTO credits VALUES("318","Patrick Trummer");
INSERT INTO credits VALUES("441","Patrik Hutter");
INSERT INTO credits VALUES("350","Patrik Maier");
INSERT INTO credits VALUES("271","Paul Melbinger");
INSERT INTO credits VALUES("418","Paul Schreiner");
INSERT INTO credits VALUES("185","Peter Kapfer");
INSERT INTO credits VALUES("276","Peter Pranter");
INSERT INTO credits VALUES("114","Peter Schmidl");
INSERT INTO credits VALUES("30","Peter Tielsch");
INSERT INTO credits VALUES("40","Peter Treitler");
INSERT INTO credits VALUES("466","Peter Waldert");
INSERT INTO credits VALUES("200","Petra Pupovac");
INSERT INTO credits VALUES("397","Philipp Eisner");
INSERT INTO credits VALUES("214","Philipp Koncar");
INSERT INTO credits VALUES("252","Philipp Kremers");
INSERT INTO credits VALUES("292","Philipp Neidhöfer");
INSERT INTO credits VALUES("361","Philipp Pfleger");
INSERT INTO credits VALUES("392","Philipp Purgaj");
INSERT INTO credits VALUES("159","Philipp Taferner");
INSERT INTO credits VALUES("248","Philipp Weissensteiner");
INSERT INTO credits VALUES("359","Phillip Goriup");
INSERT INTO credits VALUES("82","Piotr Schmidtke");
INSERT INTO credits VALUES("140","Pulkit Chouhan");
INSERT INTO credits VALUES("19","Ralph Samer");
INSERT INTO credits VALUES("148","Raphael Sommer");
INSERT INTO credits VALUES("273","Rayna Nikolova");
INSERT INTO credits VALUES("430","Reinhard Hütter");
INSERT INTO credits VALUES("447","Reinhold Seiss");
INSERT INTO credits VALUES("237","Rene Obendrauf");
INSERT INTO credits VALUES("400","Richard Aigner");
INSERT INTO credits VALUES("293","Richard Schumi");
INSERT INTO credits VALUES("24","Robert Painsi");
INSERT INTO credits VALUES("406","Robert Riedl");
INSERT INTO credits VALUES("158","Roland Dutzler");
INSERT INTO credits VALUES("317","Roland Urbano");
INSERT INTO credits VALUES("33","Roman Mauhart");
INSERT INTO credits VALUES("309","Roxane Koitz");
INSERT INTO credits VALUES("212","Rudolf Andreas Stumptner");
INSERT INTO credits VALUES("238","Rudolf Josef Wagner");
INSERT INTO credits VALUES("320","Rudolf Weißenbacher");
INSERT INTO credits VALUES("223","Sachi Alana Williamson");
INSERT INTO credits VALUES("133","Safdar Zaman");
INSERT INTO credits VALUES("224","Saif Aldeen Alsaifi");
INSERT INTO credits VALUES("262","Samir Ramadani");
INSERT INTO credits VALUES("197","Samitha Priyanath Jayathilaka");
INSERT INTO credits VALUES("390","Samuel Sprung");
INSERT INTO credits VALUES("74","Sander Latour");
INSERT INTO credits VALUES("215","Sandra Fuchs");
INSERT INTO credits VALUES("91","Sareh Choupani");
INSERT INTO credits VALUES("429","Sebastian Gabl");
INSERT INTO credits VALUES("330","Sebastian Krell");
INSERT INTO credits VALUES("398","Sebastian Schrimpf");
INSERT INTO credits VALUES("27","Sercan Akpolat");
INSERT INTO credits VALUES("213","Severin Holzer-Graf");
INSERT INTO credits VALUES("65","Shinyoung Kim");
INSERT INTO credits VALUES("195","Simge Sezgin");
INSERT INTO credits VALUES("267","Simone Lemmerer");
INSERT INTO credits VALUES("73","Sjoerd Dirk Meijer");
INSERT INTO credits VALUES("141","Smiai Oussama");
INSERT INTO credits VALUES("403","Stefan Bürscher");
INSERT INTO credits VALUES("49","Stefan Galler");
INSERT INTO credits VALUES("108","Stefan Hohenwarter");
INSERT INTO credits VALUES("12","Stefan Jaindl");
INSERT INTO credits VALUES("34","Stefan Mayer");
INSERT INTO credits VALUES("289","Stefan Neureiter");
INSERT INTO credits VALUES("193","Stefan Oberacher");
INSERT INTO credits VALUES("263","Stefan Padureanu");
INSERT INTO credits VALUES("242","Stefan Pointner");
INSERT INTO credits VALUES("448","Stefan Reichnauer");
INSERT INTO credits VALUES("53","Stefan Simon");
INSERT INTO credits VALUES("13","Stephan Fellhofer");
INSERT INTO credits VALUES("346","Stephan Frühwirt");
INSERT INTO credits VALUES("203","Suemeyra Mutlu");
INSERT INTO credits VALUES("75","Tatiyana Domanova");
INSERT INTO credits VALUES("329","Theresa Egger");
INSERT INTO credits VALUES("331","Thomas Anderhuber");
INSERT INTO credits VALUES("356","Thomas Fötschl");
INSERT INTO credits VALUES("284","Thomas Fuchs");
INSERT INTO credits VALUES("226","Thomas Gruber");
INSERT INTO credits VALUES("410","Thomas Hirsch");
INSERT INTO credits VALUES("106","Thomas Holzmann");
INSERT INTO credits VALUES("206","Thomas Huber");
INSERT INTO credits VALUES("47","Thomas Kaufmann");
INSERT INTO credits VALUES("341","Thomas Kohl");
INSERT INTO credits VALUES("290","Thomas Kriechbaumer");
INSERT INTO credits VALUES("216","Thomas Kugi");
INSERT INTO credits VALUES("311","Thomas Laubreiter");
INSERT INTO credits VALUES("445","Thomas Leh");
INSERT INTO credits VALUES("373","Thomas Lienhart");
INSERT INTO credits VALUES("153","Thomas Loidolt");
INSERT INTO credits VALUES("342","Thomas Mauerhofer");
INSERT INTO credits VALUES("270","Thomas Prem");
INSERT INTO credits VALUES("143","Thomas Rosmarin");
INSERT INTO credits VALUES("25","Thomas Schranz");
INSERT INTO credits VALUES("35","Tobias Gritschacher");
INSERT INTO credits VALUES("337","Tobias Ibounig");
INSERT INTO credits VALUES("220","Tobias Oblak");
INSERT INTO credits VALUES("431","Tobias Striemitzer");
INSERT INTO credits VALUES("165","Tobias Stumpfl");
INSERT INTO credits VALUES("107","Tom Spiss");
INSERT INTO credits VALUES("218","Tomislav Ausperger");
INSERT INTO credits VALUES("240","Valentin Kassarnig");
INSERT INTO credits VALUES("50","Valentin Rock");
INSERT INTO credits VALUES("39","Vesna Krnjic");
INSERT INTO credits VALUES("287","Viktoria Schlaipfer");
INSERT INTO credits VALUES("88","Voraya Satitpatanaphan");
INSERT INTO credits VALUES("62","Walter Tang");
INSERT INTO credits VALUES("368","Werner Arnus");
INSERT INTO credits VALUES("72","Wijnand Baretta");
INSERT INTO credits VALUES("79","Witold Kranas");
INSERT INTO credits VALUES("417","Wolfgang Karl");
INSERT INTO credits VALUES("454","Wolfgang Slany");
INSERT INTO credits VALUES("20","Wolfgang Wintersteller");
INSERT INTO credits VALUES("76","Xenia Beltran");
INSERT INTO credits VALUES("77","Yolanda Ursa");
INSERT INTO credits VALUES("399","Zulfiqar Ali");



DROP TABLE news;

CREATE TABLE `news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `headline` text NOT NULL,
  `date` datetime NOT NULL,
  `text` text NOT NULL,
  `image` text NOT NULL,
  `link` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8;

INSERT INTO news VALUES("1","Educators\' platform launched!","2016-01-30 00:00:00","Find, contribute, and share curricular material and tutorials about how Pocket Code can be used in schools!","educatrobat.jpg","http://edu.catrob.at/");
INSERT INTO news VALUES("2","Be part of the #AliceGameJam with Pocket Code and Scratch!","2015-12-07 00:00:00","Participate in the Alice Game Jame with Pocket Code and Scratch during the Computer Science Education week from 12 7th to 13th! Create and design your own Alice themed game or story and share it with us!<br/>All information needed and some cool tutorial and media-stuff can be found on the special event website!<br/>Let\'s code and be part of something big!","AGJ_HoC.jpg","http://www.alicegamejam.com");
INSERT INTO news VALUES("3","Google supports Pocket Code to teach children how to code","2015-11-19 00:00:00","Fundings by Google help us to reach out for children all over the world and give them the chance to learn how to code with Pocket Code! Schools and teenagers worldwide are already using Pocket Code and create their own apps and games, to get prepared for the digital future. Thanks to Google we even can reach out for more children and provide them additional materials and tutorials!","PC_worldwide.jpg","https://growthengine.withgoogle.com/intl/en-eu/voices#card-story/5452329046245376");
INSERT INTO news VALUES("4","Pocket Code featured at the Lovie Letters","2015-11-02 00:00:00","Find Pocket Code on the Lovie Letters presented by Google!<br />Interesting facts about the project, its history and the people behind it!","lovie_letters.jpg","http://www.lovieletters.eu/#/projects/68");
INSERT INTO news VALUES("5","Pocket Code supports Phiro robot, a staff pick on kickstarter.com!","2015-11-02 00:00:00","The Phiro Pro robot can be controlled entirely through Pocket Code!<br /><b>UPDATE:</b> Funding goal achieved after only five days, with 32 left to go!","PhiroKickstarter.jpg","http://catrob.at/PhiroKickstarter");
INSERT INTO news VALUES("6","Pocket Code and the No One Left Behind project won the ICT 2015 \'Young Minds\' Award - Grand Prix Best Connect Exhibitor Award!","2015-10-26 00:00:00","Together with the Human Brain project, we won the prize for the best exhibitor at the Horizon2020 conference of the European Commission!","ict2015.jpg","http://catrob.at/ict2015bestexhibitor");
INSERT INTO news VALUES("7","Pocket Code won a Lovie Award and a People\'s Lovie Award!","2015-10-13 00:00:00","Pocket Code has been named a Silver Winner of the Lovie Awards and a winner of the People\'s Lovie Awards.<br>Thank you for your votes and support!","lovies2015_winner.jpg","http://winners.lovieawards.eu/");
INSERT INTO news VALUES("8","Be part of the Alice Game Jam during #CodeWeekEU!","2015-10-10 00:00:00","Create your own Alice themed Game, App or Story ?with Pocket Code!","AliceGameJamEU.jpg","http://www.alicegamejam.eu/");
INSERT INTO news VALUES("9","Pocket Code now has a media library!","2015-09-21 00:00:00","Please consider creating and contributing images and sounds!","medialibrary.jpg","https://plus.google.com/+WolfgangSlany/posts/Anv1NtJAnNz");
INSERT INTO news VALUES("10","We are looking for translators!","2015-09-05 00:00:00","Please help us to reach out to even more kids by translating our apps to your language!","localization.jpg","https://plus.google.com/+WolfgangSlany/posts/ZW9h2ndnq9M");
INSERT INTO news VALUES("11","Pocket Code featured in Google\'s official \"Tech Tips from Teachers\" YouTube channel!","2015-08-04 00:00:00","The kids featured in the video are from our partner school in Graz, Austria, near our headquarters!","TechTipsFromTeachers.jpg","http://catrob.at/gttft");
INSERT INTO news VALUES("12","Pocket Code fully supports Lego Mindstorms NXT robot programming!","2015-07-15 00:00:00","You only need your Android smartphone to give your robot a face, a voice, and computer vision!","LegoMindstormsNXT.jpg","https://plus.google.com/+WolfgangSlany/posts/4xsTm2tyrM4");
INSERT INTO news VALUES("13","Pocket Code now allows to create real Android apps!","2015-06-12 00:00:00","You can download your Catrobat program after uploading it first to the sharing site!","DownloadAsApp.jpg","https://plus.google.com/+WolfgangSlany/posts/huafmHDWvh1");
INSERT INTO news VALUES("14","Tatiyana Domanova is awarded Google Anita Borg Memorial Scholarship!","2015-05-22 00:00:00","Catrobat team member and former Google Summer of Code student receives prestigious scholarship from Google!","AnitaBorg.jpg","http://www.google.co.uk/anitaborg/emea/index.html");
INSERT INTO news VALUES("15","No One Left Behind research project funded by European Union!","2015-05-19 00:00:00","Centers on Pocket Code for game based learning, focuses on inclusion!","NOLB.jpg","http://catrob.at/nolb");
INSERT INTO news VALUES("16","Catrobat is awarded highly competitive CS4HS grant by Google!","2015-04-29 00:00:00","Will be used to create a massive open online course (MOOC) on Pocket Code!<br/><b>UPDATE</b> (8 11 2015): First parts are available on https://edu.catrob.at/","cs4hs.jpg","http://catrob.at/cs4hs");
INSERT INTO news VALUES("17","Catrobat article on Google\'s Open Source blog!","2015-02-13 00:00:00","Our Google Summer of Code 2014 wrap-up is featured on Google\'s Open Source blog!","google-summer-of-code-2014-logo.jpg","http://google-opensource.blogspot.com/2015/02/google-summer-of-code-wrap-up-catrobat.html");
INSERT INTO news VALUES("18","Pocket Code at the Global Games Jam 2015!","2015-01-23 00:00:00","Catrobat took part at GGJ\'2015 held at GameCity in Nottingham!","ggj2015.jpg","https://plus.google.com/111699067405204652905/posts/V7sjhudPCVK");
INSERT INTO news VALUES("19","Beyond One Hour of Code!","2014-12-09 00:00:00","Pocket Code is featured on code.org/learn/beyond under \"Tutorial apps for phones and tablets\"!","hourofcode2014.jpg","http://code.org/learn/beyond");
INSERT INTO news VALUES("20","Programmieren am Handy nach dem Legoprinzip!","2014-11-26 00:00:00","Newspaper article on Catrobat (in German language)!","DerStandard_20141126.jpg","http://catrob.at/20141126");
INSERT INTO news VALUES("21","Create an Android game in less than one hour!","2014-10-11 00:00:00","Pocket Code is featured during the European Code Week!","Hour-of-code-promotion_small_2.jpg","https://pocketcode.org/hourOfCode");
INSERT INTO news VALUES("22","Take a crash course in fun!","2014-09-04 00:00:00","Pocket Code featured by Google in back-to-school promotion!","Google_play_learning_start_here_20140829.jpg","http://catrob.at/gpgbtspc");
INSERT INTO news VALUES("23","Invited talk about Pocket Code","2014-08-22 00:00:00","Forthcoming features presented at the Constructionism conference","constructionism.jpg","http://youtu.be/BadcMBS5WgM");
INSERT INTO news VALUES("24","Scratch team visits Catrobat HQ to start collaboration","2014-08-18 00:00:00","Mitch Resnick gave a talk on Sowing the seeds for a more creative society","scratch.jpg","https://plus.google.com/102627966522470894143/posts/Drd5oi4mK5c");
INSERT INTO news VALUES("25","First Android App creation contest with Pocket Code","2014-07-07 00:00:00","The winning app will be converted into an Android app on Google Play!","www_pocketcode_org.jpg","https://plus.google.com/102627966522470894143/posts/F95q7a1oNUY");
INSERT INTO news VALUES("26","Worldwide the first app on Google Play created entirely <em>on</em> a smartphone","2014-05-08 00:00:00","Tic-Tac-Toe Master was downloaded 23,000 times from Google Play so far!","tic-tac-toe-master.jpg","http://catrob.at/gptttm");
INSERT INTO news VALUES("27","Pocket Code and Pocket Paint on Google Play for Education","2014-03-09 00:00:00","Video of our apps used in schools for STEM education!","gpfe_cover_small.jpg","http://youtu.be/75i10o_uv0U");
INSERT INTO news VALUES("28","New versions of our Apps on Google Play","2014-03-08 00:00:00","Pocket Code and Pocket Paint are out of the beta and freely available on Google Play!","pocketcode_pocketpaint_icons.jpg","http://goo.gl/3hezq0");
INSERT INTO news VALUES("29","Google Summer of Code 2014","2014-02-24 00:00:00","Google selected us for the fourth time as a Google Summer of Code mentoring organization!","GoogleSummer_2014logo_avatar.jpg","http://www.google-melange.com/gsoc/org2/google/gsoc2014/catrobat");
INSERT INTO news VALUES("30","Catrobat at the Computer Science Education Week","2013-12-09 00:00:00","Pocket Code is participating at the Computer Science Education Week!","hourofcode.jpg","http://goo.gl/E5GYT0");
INSERT INTO news VALUES("31","Catrobat is participating at the European Code Week","2013-11-29 00:00:00","Pocket Code is demonstrated at the European Code Week and Robotics Day!","codeEU-logo.jpg","http://goo.gl/RRFOcK");
INSERT INTO news VALUES("32","Google is promoting Pocket Code","2013-11-14 00:00:00","Google is promoting Pocket Code heavily during the launch of Google Play for Education!","gp-edu-apps-n7.jpg","http://goo.gl/djpvjT");
INSERT INTO news VALUES("33","Live AR.Drone programming at Scratch\'2013","2013-07-25 00:00:00","Pocket Code presentation at Scratch\'2013, including a live demo of programming a Parrot AR.Drone!","Pocket_Code_drone_live_demo_Scratch_2013_conference_w_arrow.jpg","http://goo.gl/PVuBFq");
INSERT INTO news VALUES("34","Our Apps on the OLPC Tablet","2013-07-17 00:00:00","The preliminary physics version of Pocket Code is the programming app on the new OLPC Tablet!","web-tablet_child_592x400_with_arrow.jpg","http://goo.gl/CWFSv7");
INSERT INTO news VALUES("35","National Innovation Award","2013-03-07 00:00:00","We were awarded the Austrian National Innovation Award 2013 in the category Multimedia by the Austrian Minister for Economics and Youth Development!","stprmm2013-003_kl.jpg","http://goo.gl/gBW1JF");
INSERT INTO news VALUES("36","Google Summer of Code 2016","2016-02-29 00:00:00","Google selected us for the fifth time as a Google Summer of Code mentoring organization!","summerofcode.jpg","https://summerofcode.withgoogle.com/organizations/5495166580293632/");
INSERT INTO news VALUES("37","Alice Game Jam Review","2016-03-10 00:00:00","Congratulations to the winners of the Alice Game Jam!<br/>Find a review, the winners and further information about this Game Jam on our G+ community page!","alicegamejamreview.jpg","https://plus.google.com/+CatrobatOrgAdmin/posts/TsQJsSzrUop");
INSERT INTO news VALUES("38","Massive Open Online Course on Pocket Code","2016-04-10 00:00:00","With Google\'s CS4HS award, we created a MOOC for educators that includes 18 videos, many activities and excercises, and that has its own web community!","CS4HS_MOOC.jpg","http://catrob.at/fow");
INSERT INTO news VALUES("39","Samsung and Catrobat #CodingForKids roadshow in yellow school bus","2016-05-01 00:00:00","@SamsungAT has joined forces with Catrobat to teach computational thinking skills to kids using Pocket Code using only smartphones!","SamsungRoadshow2016.jpg","http://catrob.at/CodingForKidsRoadshow");
INSERT INTO news VALUES("41","Coding skills for refugees, learned directly on their smartphones!","2016-07-01 00:07:00","<p>Pocket Code is ideally suited for young refugees to learn how to develop Apps in their own languages.</p>","Refugees2016.jpg","http://catrob.at/bdpc");
INSERT INTO news VALUES("42","Raspberry Pi, Arduino, and NFC now supported by Pocket Code!","2016-08-10 00:08:00","<p>Pocket Code is ready for your tinkering projects as well as ultra-fast prototyping of mobile IOT (Internet Of Things) apps connected to real hardware.</p>","iot.jpg","http://catrob.at/iot");



